### ISSUE TITLE
Not linking because of rtc memory

### ISSUE THREAD

**Issue by on7lds** [Edzelf/ESP32Radio-V2#121]
Trying to compile the most recent version, but it gives me (even with no changes in config.h)

c:/users/me/.platformio/packages/toolchain-xtensa32/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32\firmware.elf section `.rtc_noinit' will not fit in region `rtc_slow_seg'
c:/users/me/.platformio/packages/toolchain-xtensa32/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: RTC_SLOW 
segment data does not fit.
c:/users/me/.platformio/packages/toolchain-xtensa32/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: region `rtc_slow_seg' overflowed by 644 bytes

**Comment by Edzelf** [comment]
Try to decrease MAXKEYS.Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: on7lds ***@***.***> Datum: 30-07-2023  15:29  (GMT+01:00) Aan: Edzelf/ESP32Radio-V2 ***@***.***> Cc: Subscribed ***@***.***> Onderwerp: [Edzelf/ESP32Radio-V2] Not linking because of rtc memory (Issue #121) 
Trying to compile the most recent version, but it gives me (even with no changes in config.h)
c:/users/me/.platformio/packages/toolchain-xtensa32/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32\firmware.elf section .rtc_noinit' will not fit in region rtc_slow_seg'
c:/users/me/.platformio/packages/toolchain-xtensa32/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: RTC_SLOW
segment data does not fit.
c:/users/me/.platformio/packages/toolchain-xtensa32/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: region `rtc_slow_seg' overflowed by 644 bytes

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Edzelf/ESP32Radio-V2/issues/121",
"url": "https://github.com/Edzelf/ESP32Radio-V2/issues/121",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
